## origin story for Ekaterinburg_IP_9.xlsx, found in inst/sheets

## https://github.com/hadley/readxl/issues/80
## OP says:
## readxl version 0.1.0
## There is a problem with reading some xlsx files (not the ones generated by
## Google Docs - this is some other xlsx generating BI) please try the
## following:
## download.file("https://raw.githubusercontent.com/e-kotov/tmp/master/Ekaterinburg_IP_9.xlsx",
##                method = "curl", dest = "Ekaterinburg_IP_9.xlsx")
## x <- read_excel("Ekaterinburg_IP_9.xlsx", skip = 5)
## It returns " Error: Couldn't find 'xl/worksheets/sheet1.xml'".
##
## As soon as the file in question is opened in Excel and re-saved, it is loaded
## with no problem.

download.file("https://raw.githubusercontent.com/e-kotov/tmp/master/Ekaterinburg_IP_9.xlsx",
              method = "curl", dest = "Ekaterinburg_IP_9.xlsx")
## then moved to inst/sheets

## opened xlsx in Excel and did Save As .... to create
## inst/sheets/Ekaterinburg_IP_9-RESAVED.xlsx
## in order to compare the underlying XML
